### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zribe** [dnmalenke/Calc2KeyCE#7]
Traceback (most recent call last):
  File "main.py", line 22, in <module>
  File "clr_loader/__init__.py", line 40, in get_coreclr
  File "clr_loader/hostfxr.py", line 13, in __init__
  File "clr_loader/ffi/__init__.py", line 28, in load_hostfxr
RuntimeError: Could not find a suitable hostfxr library in /usr/local/share/dotnet
[18198] Failed to execute script 'main' due to unhandled exception!
Exception ignored in: <function DotnetCoreRuntime.__del__ at 0x11390b940>
Traceback (most recent call last):
  File "clr_loader/hostfxr.py", line 88, in __del__
  File "clr_loader/hostfxr.py", line 83, in shutdown
AttributeError: 'DotnetCoreRuntime' object has no attribute '_handle'

i am using macos air m1

**Comment by dnmalenke** [comment]
ARM is not currently supported.
